@startuml Amplifier-Strategy-2
!theme toy 
title Amplifier-Strategy-2
start

:from part 1; 

' // Amplifiers want to avoid getting attacked, just loiter and sense other robots
' :int radius = rc.getType().actionRadiusSquared;
' :Team opponent = rc.getTeam().opponent();
' :RobotInfo[] enemies = rc.senseNearbyRobots(radius, opponent);
' :int lowestHealth = 1000;
' :int smallestDistance = 100;
' :RobotInfo target = null;
' :Communication.clearObsoleteEnemies(rc);
if (if enemies.length > 0) then (true)
    :loop thru enemies;
    :target will be closestWeakest enemy;
    while (while RobotInfo enemy: enemies) then (true)
        :Communication.reportEnemy(rc, enemy.location);
        :int enemyHealth = enemy.getHealth();
        :int enemyDistance = enemy.getLocation().distanceSquaredTo(rc.getLocation());
        if (if enemyHealth < lowestHealth && enemy.getType() != RobotType.HEADQUARTERS) then (true)
            :target = enemy;
            :lowestHealth = enemyHealth;
            :smallestDistance = enemyDistance;
        else if (if enemyHealth == lowestHealth) then (true)
            if (if enemyDistance < smallestDistance) then (true)
                :target = enemy;
                :smallestDistance = enemyDistance;
            else (no)
            endif    
        endif
    endwhile
else (no)
endif    

:Communication.tryWriteMessages(rc);

:Continue to part3; 
stop
@enduml


