@startuml Carrier-Strategy-2
!theme toy 
title Carrier-Strategy-2
start

:from part1; 

if (if canTakeAnchor(STANDARD)==true) then (true) 
    :takeAnchor(hqLoc,STANDARD); 
    :anchorMode=true;
else (no)
endif

if (if anchorMode==true) then (true) 
    :takeAnchor(hqLoc,STANDARD); 
    :anchorMode=true;
else (no)
    if(if islandLoc == null) then (true)
    :find available island;
    while (loop thru island array)
        :find any available island;
        :break;
    endwhile  
    if(if islandLoc is still null) then (true)
    :there are no available islands;
    else (no)
    :found an island;
    endif
endif

:Continue to part3; 
stop
@enduml


' goto lab

' --> "placeholder"

' if "turnCount == 1" then
'   -->[true] "addHeadquarters" as a1
' else
'   if "turnCount == 2" then
'     -->[true] "updateHeadquarters" as a3
'   else
'     if "canBuildAnchor" then
'       -left->[true] "buildAnchor(STANDARD)"
'     else
'       ' while ("numFleetAmplifiersBuilt != 2")
'           ' while ("canCreateAmplifier") 
'             ' :Build Amplifier;            
'           ' endwhile  
'       ' endwhile  
'       ' detach
'       if "canCreateCarrier" then
'         -left->[true] "createRobot(CARRIER)"
'       else
'         if "canCreateLauncher" then
'           -left->[true] "createRobot(LAUNCHER)"
'         else
'           if "canCreateBooster" then
'             -left->[true] "createRobot(BOOSTER)"
'           else
'             if "canCreateDestabilizer" then
'               -left->[true] "createRobot(DESTABILIZER)"
'             else
'               -->[true] "yield (end turn)"
'             endif
'           endif
'         endif
'       endif
'     endif
'   endif
' endif

' :HQ & every robot is called every turn;
' if (if turnCount == 1) then (true) 
' :addHeadquarters; 
' else (no)
' endif
' if (if turnCount == 2) then (true) 
' :updateHeadquarters; 
' else (no)
' endif
' if (if canBuildAnchor) then (true) 
' :buildAnchor(STANDARD); 
' else (no)
' endif
' while ("if numFleetAmplifiersBuilt != 2")
'     while ("if canCreateAmplifier") 
'       :Build Amplifier;            
'     endwhile  
' endwhile  
