@startuml Carrier-functions-scanWells-1
!theme toy 
title Carrier-functions-scanWells-1
start

' static void scanWells(RobotController rc) throws GameActionException {

:scanWells(RobotController rc);
:WellInfo[] wells = rc.senseNearbyWells();

:numWells = wells.length;

if(if wells.length > 0) then (true)
    :wellDetails = "";
    :wellLoc = wells[0].getMapLocation();
    :get a MapLocation for each island;

    while (for(WellInfo well : wells) ))
        :this is all commented out;
        if (if rc.senseTeamOccupyingIsland(well) == Team.NEUTRAL) then (true)
            :MapLocation[] locs = rc.senseNearbyIslandLocations(well);
            if(if locs.length > 0) then (true)
                :islandLoc = locs[0];
                :break;
            else (no)
            endif
        else (no)
        endif
        :Communication.updateWellInfo(rc, well);
    endwhile
else (no)
endif


:return void; 
stop
@enduml

' // logDetails = rc.getTeam() + ":"
' // + rc.getType() + "#" 
' // + rc.getID()  
' logDetails = " Health: " + rc.getHealth()  
' + " Location: " + rc.getLocation()
' + " RobotCount: " + rc.getRobotCount()
' + " numWells: " + numWells
' + " AD: " + rc.getResourceAmount(ResourceType.ADAMANTIUM) 
' + " MN: " + rc.getResourceAmount(ResourceType.MANA)  
' + " EX: " + rc.getResourceAmount(ResourceType.ELIXIR)
' // + " getClosestEnemy: " + Communication.getClosestEnemy(rc)  
' + " NumAnchors: " + rc.getNumAnchors(Anchor.STANDARD);   

' :addWell(RobotController rc, WellInfo well)
' :MapLocation me = rc.getLocation();
' while (for (int i = 0; i < MAX_STARTING_WELLS; i++)) 
'     if (rc.readSharedArray(i) == 0) then (true)
'         :rc.writeSharedArray(i, locationToInt(rc, me));
'         :break;
'     else (no)
'     endif
' endwhile


