@startuml Carrier-functions-depositResource-1
!theme toy 
title Carrier-functions-depositResource-1
start

:depositResource(RobotController rc, ResourceType type);
:int amount = rc.getResourceAmount(type);
if(if amount > 0) then (true)
    if(if rc.canTransferResource(hqLoc, type, amount)) then (true) 
        :rc.transferResource(hqLoc, type, amount);
    else (no)
    endif
else (no)
endif

:return void; 
stop
@enduml

' :addWell(RobotController rc, WellInfo well)
' :MapLocation me = rc.getLocation();
' while (for (int i = 0; i < MAX_STARTING_WELLS; i++)) 
'     if (rc.readSharedArray(i) == 0) then (true)
'         :rc.writeSharedArray(i, locationToInt(rc, me));
'         :break;
'     else (no)
'     endif
' endwhile


