@startuml Carrier-functions-scanWells-1
!theme toy 
title Carrier-functions-scanWells-1
start

' static void scanWells(RobotController rc) throws GameActionException {
' WellInfo[] wells = rc.senseNearbyWells();

' numWells = wells.length;

' // logDetails = rc.getTeam() + ":"
' // + rc.getType() + "#" 
' // + rc.getID()  
' logDetails = " Health: " + rc.getHealth()  
' + " Location: " + rc.getLocation()
' + " RobotCount: " + rc.getRobotCount()
' + " numWells: " + numWells
' + " AD: " + rc.getResourceAmount(ResourceType.ADAMANTIUM) 
' + " MN: " + rc.getResourceAmount(ResourceType.MANA)  
' + " EX: " + rc.getResourceAmount(ResourceType.ELIXIR)
' // + " getClosestEnemy: " + Communication.getClosestEnemy(rc)  
' + " NumAnchors: " + rc.getNumAnchors(Anchor.STANDARD);   


' if(wells.length > 0) {
'     wellDetails = "";
'     wellLoc = wells[0].getMapLocation();
'     // get a MapLocation for each island
'     for(WellInfo well : wells) {
'         // if(rc.senseTeamOccupyingIsland(well) == Team.NEUTRAL) {
'         //     MapLocation[] locs = rc.senseNearbyIslandLocations(well);
'         //     if(locs.length > 0) {
'         //         islandLoc = locs[0];
'         //         break;
'         //     }
'         // }

'         Communication.updateWellInfo(rc, well);


:return void; 
stop
@enduml

' :addWell(RobotController rc, WellInfo well)
' :MapLocation me = rc.getLocation();
' while (for (int i = 0; i < MAX_STARTING_WELLS; i++)) 
'     if (rc.readSharedArray(i) == 0) then (true)
'         :rc.writeSharedArray(i, locationToInt(rc, me));
'         :break;
'     else (no)
'     endif
' endwhile


