@startuml Carrier-Strategy-1
!theme toy 
title Carrier-Strategy-1
start

:Called on every turn; 

if (if turnCount == 2) then (true) 
:updateHeadquartersInfo(rc); 
else (no)
endif
if (if hqLoc == null) then (true) 
:scanHQ hqLoc; 
else (no)
endif
if (if wellLoc == null) then (true) 
:scanWells wellLoc; 
else (no)
endif

:depositResource(rc, ADMANTIUM); 

:depositResource(rc, MANA); 

if (if canTakeAnchor(STANDARD)==true) then (true) 
:takeAnchor(hqLoc,STANDARD); 
:anchorMode=true;
else (no)
endif

:Continue to part2; 
stop
@enduml

