@startuml Carrier-functions-scanHQ-1
!theme toy 
title Carrier-functions-scanHQ-1
start

' static void scanHQ(RobotController rc) throws GameActionException {
' RobotInfo[] robots = rc.senseNearbyRobots();
' for(RobotInfo robot : robots) {
'     if(robot.getTeam() == rc.getTeam() && robot.getType() == RobotType.HEADQUARTERS) {
'         hqLoc = robot.getLocation();
'         negativeHQLoc = robot.getLocation().translate( -1 * (rc.getMapWidth() - 1), -1 * (rc.getMapHeight() - 1));
'         int x = -1 * negativeHQLoc.x;
'         int y = -1 * negativeHQLoc.y;

'         inverseHQLoc = new MapLocation(x, y); 
'         break;

:return void; 
stop
@enduml

' :addWell(RobotController rc, WellInfo well)
' :MapLocation me = rc.getLocation();
' while (for (int i = 0; i < MAX_STARTING_WELLS; i++)) 
'     if (rc.readSharedArray(i) == 0) then (true)
'         :rc.writeSharedArray(i, locationToInt(rc, me));
'         :break;
'     else (no)
'     endif
' endwhile


