@startuml Carrier-functions-scanIslands-1
!theme toy 
title Carrier-functions-scanIslands-1
start

:static void scanIslands(RobotController rc);
:int[] ids = rc.senseNearbyIslands();
while (for(int id : ids)) then (true)
    if(if rc.senseTeamOccupyingIsland(id) == Team.NEUTRAL) then (true)
        :MapLocation[] locs = rc.senseNearbyIslandLocations(id);
        if(if locs.length > 0) then (true)
            :islandLoc = locs[0];
            :break;
        else (no)
        endif
    :Communication.updateIslandInfo(rc, id);
    else (no)
    endif
endwhile

:return void; 
stop
@enduml

' :addWell(RobotController rc, WellInfo well)
' :MapLocation me = rc.getLocation();
' while (for (int i = 0; i < MAX_STARTING_WELLS; i++)) 
'     if (rc.readSharedArray(i) == 0) then (true)
'         :rc.writeSharedArray(i, locationToInt(rc, me));
'         :break;
'     else (no)
'     endif
' endwhile


