@startuml Headquarters-Strategy-proposed-2
title Headquarters-Strategy-proposed-2
start
if (turnCount==1?) then (yes)
'space label only for alignment
label sp_lab0
label sp_lab1
'real label
label lab
:shared;
else (no)
if (turnCount==2?) then (yes)
label sp_lab2
goto sp_lab1
else
:nonShared;
endif
endif
:merge;
@enduml