@startuml "Headquarters-Strategy"

!theme toy 

(*) --> if "turnCount == 1" then
  -->[true] "addHeadquarters" as a1
else
  if "turnCount == 2" then
    -->[true] "updateHeadquarters" as a3
  else
    if "canCreateCarrier" then
      -left->[true] "createRobot(CARRIER)"
    else
      if "canCreateLauncher" then
        -left->[true] "createRobot(LAUNCHER)"
      else
        if "canCreateAmplifier" then
          -left->[true] "createRobot(AMPLIFIER)"
        else
          if "canCreateBooster" then
            -left->[true] "createRobot(BOOSTER)"
          else
            if "canCreateBooster" then
              -left->[true] "createRobot(DESTABILIZER)"
            else
              -->[true] "yield (end turn)"
            endif
          endif
      endif
    endif
  endif

' else

'   ->[false] "action 2"

endif

' a3 --> if "last test" then
'   --> "action 7"
' else
'   -> "action 8"
' endif
@enduml

' (*) --> if "turnCount == 1" then

'   -->[true] "addHeadquarters"

'   if "turnCount == 2" then
'     -> "updateHeadquarters" as a3
'   else
'     if "canCreateCarrier" then
'       -left-> "createRobot(CARRIER)"
'     else
'       --> "action 6"
'     endif
'   endif

' else

'   ->[false] "action 2"

' endif

' a3 --> if "last test" then
'   --> "action 7"
' else
'   -> "action 8"
' endif
