@startuml "Headquarters-Strategy"
(*) --> if "turnCount == 1" then

  -->[true] "addHeadquarters"

  if "turnCount == 2" then
    -> "updateHeadquarters" as a3
  else
    if "canCreateCarrier" then
      -left-> "createRobot(CARRIER)"
    else
      --> "action 6"
    endif
  endif

else

  ->[false] "action 2"

endif

a3 --> if "last test" then
  --> "action 7"
else
  -> "action 8"
endif
@enduml

' (*) --> if "turnCount == 1" then

'   -->[true] "addHeadquarters"

'   if "turnCount == 2" then
'     -> "updateHeadquarters" as a3
'   else
'     if "canCreateCarrier" then
'       -left-> "createRobot(CARRIER)"
'     else
'       --> "action 6"
'     endif
'   endif

' else

'   ->[false] "action 2"

' endif

' a3 --> if "last test" then
'   --> "action 7"
' else
'   -> "action 8"
' endif
